name: get changed file directory
on:
  push:
    branches: 
      - main
    paths:
      - "helm-charts/**/Charts.yaml"

jobs:
  get-cwd:
    name: get-cwd
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: podcastle-repos
      HELM_REPO_NAME: podcastle-helm-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup-yq
        run: |-
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            dirname "$file"
          done

