name: get changed file directory
on:
  push:
    branches: 
      - main
    paths:
      - "helm-charts/**/Charts.yaml"

jobs:
  get-cwd:
    name: get-cwd
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: podcastle-repos
      HELM_REPO_NAME: podcastle-helm-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup-yq
        run: |-
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq

      - name: Printing
        run: |-
          ls

